### ISSUE TITLE
Define a block and item JSON format

### ISSUE THREAD

**Issue by cpw** [MinecraftForge/FAIL#1]
One of the primary purposes of the FAIL project is to abstract a lot of the guff of building a mod into a definitions file which is invariant (except for extensions) between versions. For this purpose I propose using a JSON file which loads block and item definitions into memory, defining common properties for those.

This issue is intended to capture suggestions from modders on the structure.

**Comment by smbarbour** [comment]
I would imagine that the majority of people that would use the abstraction layer vs the more in-depth stuff would just want to add simple blocks and items (i.e. a single texture for all sides of a block or a flat sprite texture for items), which the models and blockstates would normally just be a copy of the standard boilerplate things.

So, I could envision the format defining type (block or item or even more specific types like food item), texture, unlocalized name, and some common fields for the type (i.e. hardness for blocks, mining level for tools, hunger/saturation amounts for food)

**Comment by williewillus** [comment]
Interesting note: Pocket Edition/W10 Edition already do things this way (somewhat)
I'll post the json's I extracted from it in a few

**Comment by DarkGuardsman** [comment]
This is an old XML system I developed a year+ ago, its primitive but might help
https://github.com/DarkGuardsman/Artillects-Old/tree/master/src/main/java/com/builtbroken/artillects/core/creation
I use to use it to load very basic blocks and recipes. Have yet to update it and fix issues caused by MC version updates.

Here is also an entire mod JSON system developed by Maxwolf https://github.com/BuiltBrokenModding/Mad-Science/blob/master/src/main/resources/madscience.json
He went a bit overboard by making furnace style machines possible, but the code is useful to look at.

What I would recommend is taking the time to implement interfaces that help wrap existing method calls. This way it can help improve existing mods and not just provide an abstraction for JSON files. Such as right click block actions, left click actions, rotation code, etc.

Might be able to look at this project I did for college research https://github.com/BuiltBrokenModding/TileFramework which looked into different ways to abstract one of my existing systems. Which combined the TileEntity and Block class to reduce redundant code in making machines.

**Comment by williewillus** [comment]
Also since we have a fresh new opportunity we should take care to give the json keys VERY good names.
Abstract away all the terrible mcp naming >.<

**Comment by legendblade** [comment]
If adding the ability to define actions/reactions in JSON, would it be based on actual Java code, JavaScript functions inlined in the JSON, or just a generic "onRightClick": "doSomeGenericThing"?

**Comment by williewillus** [comment]
we don't wanna do the whole "implement scripting in JSON" because that's dumb
Any advanced things should be done in java, and some common basic things likle "open GUI" could have predefined JSON strings

**Comment by legendblade** [comment]
I would disagree, as simple scripts done in JavaScript could help open up modding to a broader target audience, while ensuring that the underlying interactions are done in a way that Forge supports.  While I'm not saying that an entirely new scripting language should be written and implemented, there are pre-existing JavaScript-in-Java frameworks that could be leveraged.

**Comment by williewillus** [comment]
But we're going for a JSON def format, not Javascript (at least right now)

**Comment by legendblade** [comment]
I understand; I was just throwing the idea out there, as I currently use a similar system for a mod that utilizes a sandboxed JSON-with-JS-functions configuration file.

**Comment by williewillus** [comment]
This is how PE does it right now

https://gist.github.com/williewillus/591e791306e34138db113f54d86b880b

**Comment by cpw** [comment]
@williewillus that's very interesting. 
I was thinking of **possibly** having some **very** trivial javascript-like scripting capabilities in these files, because as @legendblade points out, it does open a new audience. This is not going to supercede anything you can do today though, and I do want the two flavours to be able to mix without being a ghastly mess.

**Comment by ryantheleach** [comment]
Spout @Dockter @zidane @grinch Might have some thoughts and suggestions.

**Comment by DarkGuardsman** [comment]
@cpw if you do add javascript it might be useful to implement a plugin system that adds more javascript options to the JSON files. As well add a way for the JSON to define where and how to download the plugins automatically. This way more advanced mod developers can create plugins with javascript libs inside.

**Comment by asiekierka** [comment]
Calling in @calclavia @Kubuxu @StanHebben of the NOVA development team

**Comment by stanhebben** [comment]
I have been summoned.

I'm not so confident with adding javascript stuff in json. But you could add behaviors to items and blocks. There could be a set a predefined behaviours (like: "this is a crafting table" or "this is a furnace") and additional behaviors - the really new things - could be added by writing java mods / plugins.

The json defined stuff things sounds interesting to me, I will think about it further.

**Comment by RangerPJ** [comment]
I think it sounds like a great idea, cut down on some of the update time and head scratching.  Using json files, that scares me a little.  I find the json model system pretty cool for making some fancy stuff.  But when you're just trying to make a quick prototype/proof of concept block/item, making a whole bunch of file and folders in a real pain and overkill when all you want is a basic cube or item.

I'm open for sure at this new idea, but let us have full java coding for both complex and basic stuff.

Using json would allow non programmers to view and edit blocks, changing some basic stuff like hardness and light level.  Think kind of like the loot tables but for blocks and items.  Might allow for some cool stuff.

**Comment by williewillus** [comment]
You state that JSON is a "overkill" for a basic cube and item, but I'm wondering what you think is simpler than that?

it doesn't get much simpler than this: https://gist.github.com/williewillus/591e791306e34138db113f54d86b880b#file-items-js-L2-L15

**Comment by calclavia** [comment]
It depends what the JSON is meant for. JSON has its limitations. While suited for simple blocks and items, it is not very open to extension. JSON seems like it works well for stating what a block is, but not what a block can do.

Would there be other ways to define block/item behaviors externally? Is JSON simply a sort of "block properties" list? Since things like block often change in terms of "new behavior", utilizing the strategy pattern when designing the API (some sort of Entity-Component System, as implemented in NOVA) https://en.wikipedia.org/wiki/Strategy_pattern may be worth considering.

**Comment by PizzaCrust** [comment]
JSON should be optional and doing it entirely in Java should be possible.

**Comment by ryantheleach** [comment]
The entire point of this is to prevent Java classes being sent over the network for security. JSON is easily secured as it's not a language, and using another language makes it simpler to sandbox, as you don't need to worry about the 1001 things that can go wrong with Java sandboxing.

Will you be able to do this straight from Java? Yes, is there any point if it can't be serialised out to JSON? No.

**Comment by Ecu** [comment]
Not sure if this will help at all, but its a prototype I design and worked with a developer to come up with.
https://github.com/Quiddity-Modding/Redux

Figured it may be relevant as it is essentially using the JSON system to create mod content, via a scripting system with the intent that eventually we'd have servers send such mods to users.

**Comment by jamen** [comment]
I agree with @ryantheleach and @williewillus.  JSON was literally created for the purpose of being something static and readable.  Have dynamic things like methods/functions or even references to them seems like it defeats the point.

What do references to methods/functions have to do with abstraction anyways?  I don't feel like it is even relevant to some degree.

**Comment by ryantheleach** [comment]
Should probably take a look at what the json files for pocket edition / xbox / windows looks like in the friendly update, it's heading somewhat data driven.

**Comment by williewillus** [comment]
yup I already posted PE's item jsons up above - if you have the win10 edition you can easily access the install directory from the command line and copy everything out

**Comment by williewillus** [comment]
They even made entity models non-terrible/slow and moved it to json

**Comment by Madsthunder** [comment]
I think @williewillus has a point with the MCPE/WIN10 JSON file format. But in my opinion, it would be a lot more useful if the jsons allowed for cross-platform compatibility. For example, in the JSON there is an array named `onBlockRightClicked` or `onBlockTapped`, and there would be an array of strings representing methods, so say the first string is `#setBlock(pos#up(1), 'minecraft:coarse_dirt')` . That would set the block on top of the block being activated to coarse dirt.

**Comment by DarkGuardsman** [comment]
@Madsthunder If i understand you correctly that would be a nice idea. We could have handling to provide a json entries to method match system. Sorta like how javaFX does it where you can specify a method to receive click events in the java code. This would provide the option to import json from other MC versions as well to allow modders to use their own custom formatting. It would also help in the case we want to make plugins to have custom methods such as power and entity spawning.

**Comment by williewillus** [comment]
@Madsthunder `#setBlock(pos#up(1), 'minecraft:coarse_dirt')` looks extremely suspiciously like code, and code should not be embedded in data, it should be in code.

**Comment by ryantheleach** [comment]
Code is data. Data is code.

**Comment by williewillus** [comment]
@ryantheleach I love lisp but we're using Java here. The two are very distinct in this world.

**Comment by DarkGuardsman** [comment]
In all honesty, even though MC is in java does not mean we must apply java standards to our json data structures. We can make a sub-scripting language that uses json as the foundation but then contains code in the files.

**Comment by williewillus** [comment]
of course, a good medium is needed. I like how the loot tables do it. You register bits of code that run to some identifier, then simply place that identifier in the correct place to run said code.

But if we're putting things like `#setBlock(pos#up(1), 'minecraft:coarse_dirt')` in our json then that's way too brittle

**Comment by DarkGuardsman** [comment]
Ya in that exact example it could be changed but it is not too far off when we could add. In the context an example could be
```json
"onRightClick":
{
    "placeBlock":
    {
       "location":"pos#up(1)",
       "block":"minecraft:coarse_dirt"
    }
}

```
it still does the same action and does allow for some code segments

as well the location could also support ``` "location":"above" ```  or ``` "location": { "x":"0", "y":"1", "z":"0" } ``` as alteratives.

That being said in the example it would just be simpler to allow some script like code. As it is shorter and easier to understand. The issue with json, in some cases, is it makes the file much large for simple tasks.

```json
"onRightClick":"setBlock(pos#up(1), minecraft:coarse_dirt)"
```

As this would just be parsed by the json reader to produce the same result.

**Comment by williewillus** [comment]
`pos#up(1)`: what's `pos`? who decided it's named that? can I name it something else? who said it has something called `up`? who said up takes a number (in string form...)? what else does it have? This is something that a static type system (and an actual programming language) answers. The position should be described as raw data. either absolute coords or a relative offset.

`"onRightClick":"setBlock(pos#up(1), minecraft:coarse_dirt)"`
see, the problem I have is with those parentheses. it looks like you're trying to invoke a function in a json string. except json is data, and data doesn't make decisions or take actions.

Instead of stuffing it all into *one* string and having to have custom logic painstakingly get it back out, use json's native structures to declare data that code can easily make sense of.

my example would deserialize easily into something like this:
```
class SetBlockAction {
    IBlockState state;
    Vec3i offset;
}

SetBlock action = gson.deserialize(..., SetBlock.class);
world.setBlockState(pos.offset(action.offset), action.state);
```

**Comment by DarkGuardsman** [comment]
To be honest I know nothing of the json's native structures but it sounds like it would be an improvement. If this works better than we can go for it over some other use case.
 
That being said in my examples I'm trying to speak abstractly to show there might be an easier way. As the idea is to design something that is simple to use and require minimal brain power to understand. What it takes on the java code side should not be the primary focus. The focus should be on how simple it is to use the json/scripting system to develop content. Since if it becomes more difficult then the best option would be to develop the content in java.

When it comes down to each example we will have to define the existence and meaning of the syntax. As I could use the same argument against any usage in json by saying "what does x mean? and who decided how i do it?". The syntax's meaning would be defined by some rule set we provide developers when making the json data. Who decided how it works would be whoever makes the json reader. It honestly doesn't matter that much as long as the usage is simple and it works at the end of the data.

As for the exact case, location/position data would have to be relative. Doing an absolute position system would be very difficult to work with. Mainly due to being provided minimal data to work with and being unable to perform method calls. As for using ``` pos ``` it would be the simplest option as it would represent your x, y, z data. Then doing an operation of ``` #up(1) ``` would be equal to ``` pos(x,y,z) + pos(0, 1, 0) ```. As well since this doesn't use () it doesn't look like a method call. However, when considered in an abstract thought process is basically is no matter how you look at it. No matter what you do any logic is just a method call using data provided.

Anyways I really don't want to argue to point and just wanted to keep options open for whoever ends up implementing the system.

**Comment by Madsthunder** [comment]
I agree with @williewillus, since it would be much easier for the deserializer to take in `offset: [ 0, 1, 0 ]` than `pos#up`.

**Comment by williewillus** [comment]
my main point is that the json format would only be for **data**. That **data** can say "call this java code with this resourcelocation", but that data should not be code itself. If we want scripting then we should revive that one JavaScript frontend for forge, not shoehorn it into a json format. but yeah

**Comment by DarkGuardsman** [comment]
@williewillus I agree with you but keep an open mind about using scripting in json. It does do wonders when trying to represent complex actions. As well we can just leave it as an option and not include it in the standard version. The idea of implementing plugins would solve the edge case for people wanting a scripting lang.

**Comment by mcenderdragon** [comment]
I think it shoulöd be also easily posible to run commands, because the users already know how they work, and the are very powerfull and easy extend able.

**Comment by williewillus** [comment]
ooh yeah that could be a good idea

**Comment by DarkGuardsman** [comment]
That would work rather well, but other than structure it's not different than a method call. Still, we can do that instead since it would be easier to parse and define.

**Comment by Madsthunder** [comment]
If we were to go with the JSON idea, there would probably need to ba a `ResourceLocation` to `Function<Parameter list, ?>` Map.

**Comment by PizzaCrust** [comment]
Java API also?

**Comment by williewillus** [comment]
?? if you wanted a java api you would use forge directly. this is discussion about a data driven api for defining blocks/items

**Comment by DarkGuardsman** [comment]
I think he wants an API to implemented support for the data. I know I want an API myself to load plugins to handle things like power, fluids, and other details. As this would allow me to slowly migrate away from my current JSON content loading system.

**Comment by PizzaCrust** [comment]
A abstract Java API that can be alternative to JSON.

**Comment by mcenderdragon** [comment]
@PizzaCrust why add an APi if you can add Items and Blocks like now?

**Comment by williewillus** [comment]
I think the idea is you can define properties using the same block using both json and java (think c# data binding or something like that)

**Comment by DarkGuardsman** [comment]
Thought I would share this since I just finished writing a JSON for MC recipes https://github.com/BuiltBrokenModding/VoltzEngine/blob/development/src/main/resources/content/voltzengine/TestRecipe.json

Code
https://github.com/BuiltBrokenModding/VoltzEngine/tree/development/src/main/scala/com/builtbroken/mc/lib/json

**Comment by FVbico** [comment]
I've been working on creating files for mojang to use themselves, and have actually started on making block property files; they're still quite far from finished tough.

https://github.com/FVbico/MinecraftData/tree/master/minecraft/assets/minecraft/properties

Maybe it's a format you guys would like to look into.

**Comment by mcenderdragon** [comment]
I think this is not so bad but I think you should mark "item_name" is not a "hard name" but rather a variable with values like "minecraft:stick" or something like that. so for eaxmple use # or <> to mark this.

**Comment by SuperGeniusZeb** [comment]
Another thing that should be considered is the addition of a type family system, like that found in the MCPE entity behavior files. This allows for a selective, but not completely-specific way of selecting items/blocks/etc.. If you've seen the MCPE entity behavior files, you'll know what I mean... they're a lot like the OreDictionary that Forge has. So instead of "minecraft:stick", you could alternatively select anything with the "stick" type family, which could include modded items with that family. I'm not sure if the OreDictionary allows for something to be in more than one group, but this idea, if implemented in the same way as the MCPE entity files, would allow for any number of type families to be applied to a block or item, and the type families could be anything from very specific to very broad.

**Comment by DarkGuardsman** [comment]
Forge's ore dictionary does allow for an item to have more than one ore tag. Though it is limited and can not support items with NBT structures. If you take a look at my earlier comments I have recipes that support ore dictionary and normal item selection.

**Comment by 3TUSK** [comment]
[*Now there is evidence that JSON-based custom recipe will be in the incoming 1.12...*](https://www.reddit.com/r/feedthebeast/comments/612i5a)

Forgive me for off-topic.

**Comment by DarkGuardsman** [comment]
That would be on topic as it means we could just take MC's format and backport it.

**Comment by loordgek** [comment]
why close it ?
